build_from:
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.11-alpine3.18"
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.11-alpine3.18"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.11-alpine3.18"

